# Usa una versión específica de Node.js
FROM node:22.12.0

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala las dependencias usando Yarn
RUN yarn install --frozen-lockfile

# Expone el puerto de la aplicación (ajústalo si es necesario)
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["yarn", "start"]